name: Test and Depoly 

on: 
	push: 
		branches:
			- main
jobs: 
	gretting: 
		runs-on: ubuntu-latest
			steps:
				- name: SayHello: 
				  run: echo 'hello from CI'
	test: 
		runs-on: ubuntu-latest
		steps:
			- name: cloneRepo
			  uses: actions/checkout@v2

			- name: install-dep
			  run: npm install

			- name: setup-postGres
			  uses: harmon758/postgresql-action@1
			  with: 
				postgresql db: test_db
				postgresql user: tester
				postgresql password: password1

			- name: run-tests-utils
			  run: npm t utils

			- name: test-all 
			  run: PGDATABASE=test_db PGUSER=tester PGPASSWORD=password1 npm test

	deploy: 
		run-on: ubuntu-latest
		needs: test
		steps: 
			- name: clone repo
			  uses: actions/checkout@v2

			- name: deploy-to-heroku
			  uses: akhileshns/heroku-deploy@v3.12.12
			  with: 
				heroku_api_key: ${secrets.HEROKU_API_KEY}
				heroku_app_name: ${secrets.HEROKU_API_name}
				heroku_email: ${secrets.HEROKU_API_email}      